# Generated by Django 5.0 on 2023-12-18 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('сustom_authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='', upload_to='')),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=10000000)),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='BattleField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_coordinates', models.CharField(default='', max_length=1024)),
                ('size_horizontal', models.IntegerField(default=10)),
                ('size_vertical', models.IntegerField(default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='сustom_authorization.profile')),
            ],
            options={
                'verbose_name': 'игровое поле',
                'verbose_name_plural': 'игровые поля',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='сustom_authorization.profile')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.product')),
            ],
            options={
                'verbose_name': 'подарок',
                'verbose_name_plural': 'подарки',
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(default='', max_length=256)),
                ('battle_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.battlefield')),
            ],
            options={
                'verbose_name': 'корабль',
                'verbose_name_plural': 'корабли',
            },
        ),
    ]
